[[language]]
name = "python"
auto-format = true
formatter = { command = "black", args = ["-", "-q"] }

[language.config.pylsp.plugins.pycodestyle]
maxLineLength = 88

[[language]]
name = "cpp"
auto-format = true
formatter = { command = "clang-format", args = ["-style=file:/home/austreng/.config/helix/clangformat"] }

[[language]]
name = "c"
auto-format = true
formatter = { command = "clang-format", args = ["-style=file:/home/austreng/.config/helix/clangformat"] }
