[[language]]
name = "python"
auto-format = true
formatter = { command = "black", args = ["-", "-q"] }

[language.config.pylsp.plugins.pycodestyle]
maxLineLength = 88

[[language]]
name = "cpp"
auto-format = true
formatter = { command = "clang-format", args = ["-style=file:/home/austreng/.config/helix/clangformat"] }

[[language]]
name = "c"
auto-format = true
formatter = { command = "clang-format", args = ["-style=file:/home/austreng/.config/helix/clangformat"] }

[[language]]
name = "elixir"
scope = "source.elixir"
injection-regex = "elixir"
file-types = ["ex", "exs"]
roots = ["mix.exs"]
auto-format = true
diagnostic-severity = "Hint"
comment-token = "#"
indent = { tab-width = 2, unit = " " }
language-server = { command = "elixir-ls" }
