stty -ixon

alias ls="ls --color=auto"
alias grep="grep --color=auto"

bindkey "^k" up-line-or-history
bindkey "^j" down-line-or-history
bindkey "^h" backward-char
bindkey "^s" forward-char

alias man="PAGER=most man"

export PATH=$PATH:/home/austreng/.local/bin

export PS1="%B%F{blue}%m%f%b "
export RPS1="%(? %F{cyan} %F{yellow})%~%f"
