# Respect slave flow control
stty -ixon

# Navigation
bindkey "^k" up-line-or-history
bindkey "^j" down-line-or-history
bindkey "^h" backward-char
bindkey "^s" forward-char

# Spawn new shell
function new_shell {
    alacritty msg create-window --working-directory $PWD
}

zle -N new_shell
bindkey '^n' new_shell

# Resume suspended job
function ctrlz() {
if [[ $#BUFFER == 0 ]]; then
    fg >/dev/null 2>&1 && zle redisplay
else
    zle push-input
fi
}

zle -N ctrlz
bindkey '^Z' ctrlz

# Create and move into directory
function cdd {
    mkdir -p $1 && cd $1
}

# Aliases
alias octave="octave --quiet"
alias bat="bat --number --pager 'less -RFX'"
alias sed="sed --regexp-extended"
alias gdb="gdb --quiet -tui"
alias py="python"
alias ls="ls --color=auto"
alias ct="cd $(mktemp -d)"

# Basic setup
export PS1="%B%F{blue}▶%f%b "
export RPS1="%(? %F{cyan} %F{yellow})%~%f"
export MANPAGER="less -R --use-color -Dd+G -Du+b -DS+kY"
export EDITOR=/usr/bin/helix
export VISUAL=$EDITOR

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
setopt interactivecomments

# Plugins
source $HOME/.config/zsh/completion.zsh
source $HOME/.config/zsh/key-bindings.zsh

plugins=(fzf)
