stty -ixon

alias ls="ls --color=auto"
alias grep="grep --color=auto"

bindkey "^k" up-line-or-history
bindkey "^j" down-line-or-history
bindkey "^h" backward-char
bindkey "^s" forward-char

alias octave="octave --quiet"
alias cat="bat --number --pager 'less -RFX'"
alias gdb="gdb --quiet -tui"
alias py="python"
alias sicr="python /home/austreng/SecDom/Remote/sicr_compare.py"

export PATH=$PATH:/home/austreng/.local/bin

export PS1="%B%F{blue}▶%f%b "
export RPS1="%(? %F{cyan} %F{yellow})%~%f"

export XDG_CONFIG_HOME=/home/austreng/.config

export MANPAGER="less -R --use-color -Dd+G -Du+b -DS+kY"

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
setopt interactivecomments

source $HOME/.config/zsh/completion.zsh
source $HOME/.config/zsh/key-bindings.zsh

plugins=(fzf)
